import { useContext } from "react";
import { useEffect } from "react";
import { Statee } from "./context/stateContext";

import { useSelector } from "react-redux";
export default function Dates({ selectedPrinter }) {
  const {
    invoiceNumber,
    invoiceDate,
    dueDate,
    fbrInvoiceNumber,
    clientName,
    clientAddress,
    saleBy,
  } = useContext(Statee);
  const { newSalesProduct } = (state) => state.newSalesProduct;
  const { user } = useSelector((state) => state.user);
  useEffect(()=>{
    console.log(user?.user)
  },[])
  
 

  return (
    <>
      {user?.user?.printerId?.printerType === "Laser" ? (
        <>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Customer Name:</h5>
              <p>{clientName}</p>
            </div>
            <div className="consolidateLaserProductCode">
              <h5>Cell No:</h5>
              <p>{clientAddress}</p>
            </div>
          </div>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Invoice number:</h5>
              <p> {invoiceNumber}</p>
            </div>
            <div className="consolidateLaserProductCode">
              <h5>Invoice date:</h5>
              <p>{invoiceDate}</p>
            </div>
          </div>
          <div className="InvoiceLaserFirstRecordDiv">
            <div className="consolidateLaserQuantity">
              <h5>Generated By:</h5>
              <p> {user?.user?.name}</p>
            </div>
            {fbrInvoiceNumber ? (
              <>
                <div className="consolidateLaserProductCode">
                  <h5>FBR Invoice number:</h5>
                  <p> {fbrInvoiceNumber}</p>
                </div>
              </>
            ) : (
              <></>
            )}
          </div>
        </>
      ) : (<>
    
            <div className="mainDatesThermalDiv">
            <div className="SecondDivThermal">
              <h3>Customer Name:&nbsp;</h3>
              <h3>{clientName}</h3>
            </div>
            <div className="SecondDivThermal">
              <h3>Cell No:&nbsp;</h3>
              <h3> {clientAddress}</h3>
            </div>
            <div className="SecondDivThermal">
              <h3>Invoice number:&nbsp;</h3>
              <h3>{invoiceNumber}</h3>
            </div>
            <div className="SecondDivThermal">
              <h3>Invoice Date:&nbsp;</h3>
              <h3>{invoiceDate}</h3>
            </div>
            <div className="SecondDivThermal">
              <h3>FBR Invoice number:&nbsp;</h3>
              <h3>{fbrInvoiceNumber}</h3>
             
            </div> <div className="SecondDivThermal">
              <h3>Generated By:&nbsp;</h3>
              <h3>{user?.user?.name}</h3>
            </div>
          </div>  </>
        // <>
        //   <div className="InvoiceLaserFirstRecordDiv">
        //     <div className="consolidateLaserQuantity">
        //       <h5>Customer Name:</h5>
        //       <p>{clientName}</p>
        //     </div>
        //     <div className="consolidateLaserProductCode">
        //       <h5>Cell No:</h5>
        //       <p>{clientAddress}</p>
        //     </div>
        //   </div>
        //   <div className="InvoiceLaserFirstRecordDiv">
        //     <div className="consolidateLaserQuantity">
        //       <h5>Invoice number:</h5>
        //       <p> {invoiceNumber}</p>
        //     </div>
        //     <div className="consolidateLaserProductCode">
        //       <h5>Invoice date:</h5>
        //       <p>{invoiceDate}</p>
        //     </div>
        //   </div>
        //   <div className="InvoiceLaserFirstRecordDiv">
        //     <div className="consolidateLaserQuantity">
        //       <h5>Generated By:</h5>
        //       <p> {user?.user?.name}</p>
        //     </div>
        //     {fbrInvoiceNumber ? (
        //       <>
        //         <div className="consolidateLaserProductCode">
        //           <h5>FBR Invoice number:</h5>
        //           <p> {fbrInvoiceNumber}</p>
        //         </div>
        //       </>
        //     ) : (
        //       <></>
        //     )}
        //   </div>
        // </>
      )}
    </>
  );
}
