import { useContext, useEffect } from "react";
import { QURESHI_ELECTRONICS } from "../../../constants/companyNameContants";

export default function Dates({ data }) {

  return (
            <>
          <div style={{margin: "20px"}} className="mainDiv">
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5 style={{fontFamily: "Calibri"}}>Customer Name:</h5>
              <p>{data?.customerName}</p>
            </div>
            <div className="secondDiv">
              <h5 style={{fontFamily: "Calibri"}}>Cell No:</h5>
              <p>{data?.customerNumber}</p>
            </div>
          </div>
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5 style={{fontFamily: "Calibri"}}>Generated By:</h5>
              <p> {data?.saleBy}</p>
            </div>
            {
                      QURESHI_ELECTRONICS === "QURESHI_ELECTRONICS_WITH_FBR" ? (
                        <>
                         <div className="secondDiv">
                            <h5 style={{fontFamily: "Calibri"}}>FBR Invoicer Number:</h5>
                            <p> {data?.invoiceNumber}</p>
                        </div>
                        </>
                      ): (<> <div className="secondDiv">
                        <h5>Invoicer number:</h5>
                        
                        <p> {data?.id}</p>
                      </div></>)}
           
          </div>
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5>Invoice date:</h5>
              <p> {new Date(data?.createdAt).toLocaleDateString(
                      "en-GB"
                    )}</p>
            </div>
          
              <>
              {
                      QURESHI_ELECTRONICS === "QURESHI_ELECTRONICS_WITH_FBR" && (
                        <>
                         <div className="secondDiv">
                          <h5>Invoicer number:</h5>
                          <p> {data?.id}</p>
                        </div></>
                      )}
               
              </>
          </div>
          
          </div>
              {/* <div className="InvoiceSecondCont">
                <div className="InvoiceThirdCont">
                  <div className="consolidateSaleLaserdivs">
                    <h5>Customer Name:</h5>
                    <p>{invoicedata?.customerName}</p>
                  </div>
                  <div className="consolidateSaleLaserdivs">
                    <h5>Cell No:</h5>
                    <p>{invoicedata?.customerNumber}</p>
                  </div>
                  <div className="consolidateSaleLaserdivs">
                    <h5>Generated By:</h5>
                    <p>{invoicedata?.saleBy}</p>
                  </div>
                </div>
                <div className="InvoiceThirdCont">
                  <div className="consolidateSaleSecondLaserdivs">
                    <h5>Invoicer number:</h5>
                    <p>{invoicedata?.id}</p>
                  </div>
                  <div className="consolidateSaleSecondLaserdivs">
                    <h5>Invoice date:</h5>
                    <p>
                      {new Date(invoicedata?.createdAt).toLocaleDateString(
                        "en-GB"
                      )}
                    </p>
                  </div>

                  {invoicedata?.invoiceNumber ? (
                    <>
                    <div className="consolidateSaleSecondLaserdivs">
                      {
                        JSON.parse(localStorage.getItem("SoftwareWithFBR")) && (<>
                          <h5>FBR Invoicer Number:</h5>
                          <p> {invoicedata?.invoiceNumber}</p>
                        </>)
                      }
                      
                      </div>
                    </>
                    ) : (
                    <></>
                  )}
                </div>
              </div> */}
            {/* </div> */}
              {/* <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Customer Name:</h5>
                  <p>{invoicedata?.customerName}</p>
                </div>
                <div className="consolidateLaserInvoiceNumber">
                  <h5>Invoicer number:</h5>
                  <p>{invoicedata?.id}</p>
                </div>
              </div>
              <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Cell No:</h5>
                  <p>{invoicedata?.customerNumber}</p>
                </div>
                <div className="consolidateSaleLaserInvoiceNumber">
                  <h5>Invoice date:</h5>
                  <p>
                    {new Date(invoicedata?.createdAt).toLocaleDateString(
                      "en-GB"
                    )}
                  </p>
                </div>
              </div>
              <div className="InvoiceLaserFirstRecordDiv">
                <div className="consolidateLaserQuantity">
                  <h5>Generated By:</h5>
                  <p>{invoicedata?.saleBy}</p>
                </div>
                {invoicedata?.invoiceNumber ? (
                  <>
                    <div className="consolidateFRBLaserProductCode">
                      <h5>FBR Invoicer Number:</h5>
                      <p> {invoicedata?.invoiceNumber}</p>
                    </div>
                  </>
                ) : (
                  <></>
                )}
              </div> */}
              </>
  );
}
