import { useContext, useEffect } from "react";
import { useCustomState } from "../../../../Variables/stateVariables";
import { State } from "../context/ContextSales";
import { getPurchaseDetailForPreview } from "../../../../actions/purchaseAction";
export default function Dates({ selectedPrinter }) {
  const { invoicedata, setInvoicedata, setProducts, loading, setLoading } =
    useCustomState();
  const { purchaseId, setPurchaseId, purchaseRef } = useContext(State);
  const currentDate = new Date();
  let formattedDate = currentDate.toLocaleDateString("en-GB");
  useEffect(() => {
    // call();
    getspecificDataforInvoice();
  }, []);
  const getspecificDataforInvoice = async () => {
    // let result = await getPurchaseDetail(salesId);
    let result = await getPurchaseDetailForPreview(purchaseId);
    console.log(result.data);
    setInvoicedata(result.data);
    setLoading(true);
  };

  return (
    <>
      {/* {selectedPrinter === "thermal" ? (
        <div
          style={{
            width: "100%",
            overflowX: "auto",
            marginTop: "-30px",
            marginBottom: "0px",
            whiteSpace: "nowrap",
          }}
        >
          <table
            className="mt-10 table1"
            style={{ fontSize: "10px", whiteSpace: "nowrap" }}
          >
            <tbody>
              <tr
                style={{
                  marginTop: "-10px",
                  padding: "0px",
                  marginBottom: "-10px",
                }}
              >
                <td>
                  <span className="font-bold td1">Purchase From:</span> &nbsp;
                  {invoicedata?.clientName}
                </td>
              </tr>
              <tr style={{ marginTop: "-30px", marginBottom: "0px" }}>
                <td
                  className="font-bold td1"
                  style={{ marginTop: "-30px", marginBottom: "0px" }}
                >
                  <span className="font-bold td1">Invoicer number:</span> &nbsp;{" "}
                  {invoicedata?.id}
                </td>
              </tr>
              <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                <td className="font-bold td1">
                  <span className="font-bold td1">Purchase Rcpt Number:</span>{" "}
                  &nbsp; {invoicedata?.purchaseReceiptNumber}
                </td>
              </tr>
              <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
                <td>
                  <span className="font-bold td1">Invoice date:</span> &nbsp;{" "}
                  {new Date(invoicedata?.createdAt).toLocaleDateString("en-GB")}
                </td>
              </tr>
              <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                <td>
                  {" "}
                  <span className="font-bold td1">Company:</span> &nbsp;
                  {invoicedata?.purchaseCompany}
                </td>
              </tr>
              <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
                <td className="td1">
                  {invoicedata?.purchaseDate ? (
                    <li style={{ listStyle: "none" }}>
                      <span className="font-bold">Purchase Rcpt date:</span>{" "}
                      &nbsp;{" "}
                      {new Date(invoicedata?.purchaseDate).toLocaleDateString(
                        "en-GB"
                      )}
                    </li>
                  ) : (
                    <span className="font-bold">Purchase Rcpt date:</span>
                  )}
                </td>
              </tr>
              <tr>
                <td>
                  {" "}
                  <span className="font-bold td1">Generated By:</span> &nbsp;
                  {invoicedata?.purchasedBy}
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      ) : ( */}
      <div style={{ margin: "20px" }} className="mainDiv">
        <div className="DatesFirstDiv">
          <div className="firstDiv">
            <h5 style={{ fontFamily: "Calibri" }}>Purchase From:</h5>
            <p>{invoicedata?.clientName}</p>
          </div>
          <div className="secondDiv">
            <h5 style={{ fontFamily: "Calibri" }}>Invoicer number:</h5>
            <p>{invoicedata?.id}</p>
          </div>
        </div>
        <div className="DatesFirstDiv">
          <div className="firstDiv">
            <h5 style={{ fontFamily: "Calibri" }}>Purchase Rcpt Number:</h5>
            <p> {invoicedata?.purchaseReceiptNumber}</p>
          </div>
          <div className="secondDiv">
            <h5 style={{ fontFamily: "Calibri" }}>Invoice date:</h5>
            <p>
              {new Date(invoicedata?.createdAt).toLocaleDateString("en-GB")}
            </p>
          </div>
        </div>
        <div className="DatesFirstDiv">
          <div className="firstDiv">
            <h5>Company:</h5>
            <p> {invoicedata?.purchaseCompany}</p>
          </div>

          <>
            <div className="secondDiv">
              <h5>Purchase Rcpt date:</h5>

              <p>
                {" "}
                {new Date(invoicedata?.purchaseDate).toLocaleDateString(
                  "en-GB"
                )}
              </p>
            </div>
          </>
        </div>
        <div className="DatesFirstDiv">
          <div className="firstDiv">
            <h5>Generated By:</h5>
            <p> {invoicedata?.purchasedBy}</p>
          </div>

          <div className="secondDiv">
            <h5 >Store In:</h5>
            <p>
              {invoicedata?.storeIn}
            </p>
          </div>
        </div>
      </div>
      {/* <div className="InvoiceSecondCont">
                <div className="InvoiceThirdCont">
                  <div className="consolidatePurchaseLaserdivs">
                    <h5>Purchase From:&nbsp;</h5>
                    <p>{invoicedata?.clientName}</p>
                  </div>
                  <div className="consolidatePurchaseLaserdivs">
                    <h5>Purchase Rcpt Number:&nbsp;</h5>
                    <p> {invoicedata?.purchaseReceiptNumber}</p>
                  </div>
                  <div className="consolidatePurchaseLaserdivs">
                    <h5>Company:&nbsp;</h5>
                    <p> {invoicedata?.purchaseCompany}</p>
                  </div>
                  <div className="consolidatePurchaseLaserdivs">
                    <h5>Generated By:&nbsp;</h5>
                    <p> {invoicedata?.purchasedBy}</p>
                  </div>
                </div>
                <div className="InvoiceThirdCont">
                  <div className="consolidatePurchaseSecondLaserdivs">
                    <h5>Invoicer number:&nbsp;</h5>
                    <p>{invoicedata?.id}</p>
                  </div>
                  <div className="consolidatePurchaseSecondLaserdivs">
                    <h5>Invoice date:&nbsp;</h5>
                    <p>{new Date(invoicedata?.createdAt).toLocaleDateString("en-GB")}</p>
                  </div>
                  <div className="consolidatePurchaseSecondLaserdivs">
                    <h5>Purchase Rcpt date:&nbsp;</h5>
                    <p>{" "}{new Date(invoicedata?.purchaseDate).toLocaleDateString("en-GB")}</p>
                  </div>
                  <div className="consolidatePurchaseSecondLaserdivs">
                    <h5>Store In:&nbsp;</h5>
                    <p> {invoicedata?.storeIn}</p>
                  </div>
                </div>
              </div>
       */}
      {/* </>
      )} */}
    </>
  );
}
