import { useContext, useEffect, useState } from "react";
import { State } from "./context/stateContext";
import { useSelector } from "react-redux";
export default function Dates({ selectedPrinter }) {
  const {
    invoiceNumber,
    invoiceDate,
    dueDate,
    purchaseDate,
    setPurchaseDate,
    clientName,
    purchaseReceiptNumber,
    purchaseCompany,
    purchasedBy,
  } = useContext(State);
  const [purchaseBy, setPurchaseBy] = useState()
  const currentDate = new Date();
  const { user } = useSelector((state) => state.user);
  let formattedDate = currentDate?.toLocaleDateString();
  console.log(user);
  useEffect(()=>{
    setPurchaseBy(JSON.parse(localStorage.getItem('username')))
  }, [])
  return (
    <>
      {user?.user?.printerId?.printerType === "Laser" ? (
        <>
        <div className="mainDiv">
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5 style={{fontFamily: "Calibri"}}>Purchase From:</h5>
              <p>{clientName}</p>
            </div>
            <div className="secondDiv">
              <h5 style={{fontFamily: "Calibri"}}>Invoicer number:</h5>
              <p>{invoiceNumber}</p>
            </div>
          </div>
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5 style={{fontFamily: "Calibri"}}>Purchase Rcpt Number:</h5>
              <p> {purchaseReceiptNumber}</p>
            </div>
            <div className="secondDiv">
              <h5 style={{fontFamily: "Calibri"}}>Invoice date:</h5>
              <p>{formattedDate}</p>
            </div>
          </div>
          <div className="DatesFirstDiv">
            <div className="firstDiv">
              <h5>Company:</h5>
              <p> {purchaseCompany}</p>
            </div>
            {purchaseDate ? (
              <>
                <div className="secondDiv">
                  <h5>Purchase Rcpt date:</h5>
                  {purchaseDate ? (
                  <p> {purchaseDate}</p>):(<h1></h1>)}
                </div>
              </>
            ) : (
              <></>
            )}
          </div>
          <div className="DatesFirstDiv">
            {purchaseBy ? (
              <>
                <div className="firstDiv">
                  <h5>Generated By:</h5>
                  <p> {purchaseBy}</p>
                </div>
              </>
            ) : (
              <></>
            )}
          </div>
          </div>
        </>
      ) : (<>
      <div className="mainDatesThermalDiv">
        <div className="SecondDivThermal">
          <h3 >Purchase From:&nbsp;</h3>
          <h3>{clientName}</h3>
        </div>
        <div className="SecondDivThermal">
          <h3 >Invoice Number:&nbsp;</h3>
          <h3> {invoiceNumber}</h3>
        </div>
        <div className="SecondDivThermal">
          <h3 >Purchase Receipt Number:&nbsp;</h3>
          <h3>{purchaseReceiptNumber}</h3>
        </div>
        <div className="SecondDivThermal">
          <h3 >Invoice Date:&nbsp;</h3>
          <h3>{formattedDate}</h3>
        </div>
        <div className="SecondDivThermal">
          <h3 >Company:&nbsp;</h3>
          <h3>{purchaseCompany}</h3>
        </div>
        <div className="SecondDivThermal">
          <h3 >Purchase Recpt Date:&nbsp;</h3>
          {purchaseDate ? ( <h3>{purchaseDate}</h3>):(<></>)}
         
        </div> <div className="SecondDivThermal">
          <h3 >Generated By:&nbsp;</h3>
          <h3>{purchaseBy}</h3>
        </div>
      </div>
      </>
        // <div
        //   style={{
        //     width: "100%",
        //     overflowX: "auto",
        //     marginTop: "-30px",
        //     marginBottom: "0px",
        //     whiteSpace: "nowrap",
        //   }}
        // >
        //   <table
        //     className="mt-10 table1"
        //     style={{ fontSize: "10px", whiteSpace: "nowrap" }}
        //   >
        //     <tbody>
        //       <tr
        //         style={{
        //           marginTop: "-10px",
        //           padding: "0px",
        //           marginBottom: "-10px",
        //         }}
        //       >
        //         <td>
        //           <span className="purchaseDatesTitles">Purchase From:</span> &nbsp;
        //           {clientName}
        //         </td>
        //       </tr>
        //       <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        //         <td
        //           className="font-bold td1"
        //           style={{ marginTop: "-30px", marginBottom: "0px" }}
        //         >
        //           <span className="purchaseDatesTitles">Invoicer number:</span> &nbsp;{" "}
        //           {invoiceNumber}
        //         </td>
        //       </tr>
        //       <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        //         <td className="font-bold td1">
        //           <span className="purchaseDatesTitles">Purchase Rcpt Number:</span>{" "}
        //           &nbsp; {purchaseReceiptNumber}
        //         </td>
        //       </tr>
        //       <tr style={{ marginTop: "-10px", marginBottom: "0px" }}>
        //         <td>
        //           <span className="purchaseDatesTitles">Invoice date:</span> &nbsp;{" "}
        //           {formattedDate}
        //         </td>
        //       </tr>
        //       <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
        //         <td>
        //           {" "}
        //           <span className="purchaseDatesTitles">Company:</span> &nbsp;
        //           {purchaseCompany}
        //         </td>
        //       </tr>
        //       <tr style={{ marginTop: "0px", marginBottom: "0px" }}>
        //         <td className="td1">
        //           {purchaseDate ? (
        //             <li style={{ listStyle: "none" }}>
        //               <span className="font-bold">Purchase Rcpt date:</span>{" "}
        //               &nbsp; {purchaseDate.toLocaleDateString()}
        //             </li>
        //           ) : (
        //             <span className="purchaseDatesTitles">Purchase Rcpt date:</span>
        //           )}
        //         </td>
        //       </tr>
        //       <tr>
        //         <td>
        //           {" "}
        //           <span className="purchaseDatesTitles">Generated By:</span> &nbsp;
        //           {purchaseBy}
        //         </td>
        //       </tr>
        //     </tbody>
        //   </table>
        // </div>
      )}
    </>
  );
}
