import { useContext, useEffect } from "react";
// import { useCustomState } from "../../Variables/stateVariables";
import { useCustomState } from "../../../../Variables/stateVariables";
import { State } from "../context/ContextSales";
import { getSpecificSaleProduct } from "../../../../actions/saleProductAction";
import { QURESHI_ELECTRONICS } from "../../../../constants/companyNameContants";

export default function Dates({ selectedPrinter }) {
  const { invoicedata, setInvoicedata, loading, setLoading } = useCustomState();
  const { salesId } = useContext(State);

  useEffect(() => {
    getspecificDataforInvoice();
  }, []);

  const getspecificDataforInvoice = async () => {
    console.log(salesId);
    let result = await getSpecificSaleProduct(salesId);
    console.log("hice");
    // console.log(result);
    setInvoicedata(result?.data);
    setLoading(true);
  };

  return (
    <>
      {loading ? (
        <>
          <>
            <div style={{ margin: "20px" }} className="mainDiv">
              <div className="DatesFirstDiv">
                <div className="firstDiv">
                  <h5 style={{ fontFamily: "Calibri" }}>Customer Name:</h5>
                  <p>{invoicedata?.customerName}</p>
                </div>
                <div className="secondDiv">
                  <h5 style={{ fontFamily: "Calibri" }}>Cell No:</h5>
                  <p>{invoicedata?.customerNumber}</p>
                </div>
              </div>
              <div className="DatesFirstDiv">
                <div className="firstDiv">
                  <h5 style={{ fontFamily: "Calibri" }}>Generated By:</h5>
                  <p> {invoicedata?.saleBy}</p>
                </div>
                {QURESHI_ELECTRONICS === "QURESHI_ELECTRONICS_WITH_FBR" ? (
                  <>
                    <div className="secondDiv">
                      <h5 style={{ fontFamily: "Calibri" }}>
                        FBR Invoicer Number:
                      </h5>
                      <p> {invoicedata?.invoiceNumber}</p>
                    </div>
                  </>
                ) : (
                  <>
                    {" "}
                    <div className="secondDiv">
                      <h5>Invoicer number:</h5>

                      <p> {invoicedata?.id}</p>
                    </div>
                  </>
                )}
              </div>
              <div className="DatesFirstDiv">
                <div className="firstDiv">
                  <h5>Invoice date:</h5>
                  <p>
                    {" "}
                    {new Date(invoicedata?.createdAt).toLocaleDateString(
                      "en-GB"
                    )}
                  </p>
                </div>

                <>
                  {QURESHI_ELECTRONICS === "QURESHI_ELECTRONICS_WITH_FBR" ? (
                    <>
                      <div className="secondDiv">
                        <h5>Invoicer number:</h5>
                        <p> {invoicedata?.id}</p>
                      </div>
                    </>
                  ) : (
                    <>
                      {invoicedata?.returnInvoiceNo && (
                        <div className="secondDiv">
                          <h5>Return Invoice Number:</h5>
                          <p> {invoicedata?.returnInvoiceNo}</p>
                        </div>
                      )}
                    </>
                  )}
                </>
              </div>
              <div className="DatesFirstDiv">
                <>
                  {QURESHI_ELECTRONICS === "QURESHI_ELECTRONICS_WITH_FBR" &&(
                    <>
                      {invoicedata?.returnInvoiceNo && (
                        <div className="secondDiv">
                          <h5>Return Invoice Number:</h5>
                          <p> {invoicedata?.returnInvoiceNo}</p>
                        </div>
                      )}
                    </>
                  )}
                </>
              </div>
            </div>
          </>
        </>
      ) : (
        <h1></h1>
      )}
    </>
  );
}
